[package]
name = "klein-sys"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "Rust bindings to the Klein PGA3D library"
build = "build.rs"

[build-dependencies]
bindgen = "0.59.1"
cc = "1.0.70"
